# Update this
baseURL = "http://stuartnelson3.github.io"
languageCode = "en-us"
title = "stuart nelson"
theme = "smol"
paginate = 20

[markup.goldmark.renderer]
unsafe= true

# Parameters
[params]
    # subtitle = "be excellent to each other."
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"
        weight = 1

  [[menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts/"
        weight = 2

  [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "github"
        url = "https://github.com/stuartnelson3"
        weight = 1
