# Update this
baseURL = "http://stuartnelson3.github.io"
languageCode = "en-us"
title = "Stuart's Blog"
theme = "smol"

# Parameters
[params]
    subtitle = "Your blog subtitle goes here!"
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 2

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/stuartnelson3"
        weight = 1
